# Docker Compose Configuration for Sports Calendar
# Change ports if you have conflicts (e.g., WAMP, XAMPP)

services:
  # Database service
  db:
    image: mysql:8.0
    container_name: sports_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sports_network

  # Web service (PHP + Apache)
  web:
    build: ./php
    container_name: sports_web
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - sports_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sports_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - sports_network

volumes:
  db_data:

networks:
  sports_network:
    driver: bridge